version: '3'
services:
  cb:
    image: couchbase:community
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    ulimits:
      nofile: 80000
      core: 100000000
      memlock: 100000000
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD:/usr/share/nginx/html:ro"
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/cert
  server:
    build: .
    environment:
      - "YAM_DB_ADDRESS=couchbase://cb"