version: '3'
services:
  cb:
    image: couchbase:community
    volumes:
      - ./couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    ulimits:
      nofile: 80000
      core: 100000000
      memlock: 100000000
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD:/usr/share/nginx/html:ro"
      - "$PWD/js/config-dev.js:/usr/share/nginx/html/lib/config.js:ro"
#      - "$PWD/js/config.js:/usr/share/nginx/html/lib/config.js:ro"
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/cert
  server:
    build: .
    environment:
      - "YAM_DBADDRESS=couchbase://cb"
      - "YAM_CERT=/cert/srv.pem"
      - "YAM_CERTKEY=/cert/srv-key.pem"
    volumes:
      - "./cert:/cert"
    ports:
      - "1337:1337"
    links:
      - cb:cb